# Generated by Django 4.2.6 on 2024-10-16 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyrs',
            name='data_vrem',
            field=models.DateTimeField(default=datetime.datetime.now, null=True, verbose_name='когда'),
        ),
    ]
